server:
    port: 10000

system:
    appId: countryapp
    token: bWlubGlhCg==

# SPRING PROFILES
spring:
    profile: dev
    application:
        name: country
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true

    datasource:
        name:
        driverClassName: net.sf.log4jdbc.DriverSpy
        url: jdbc:log4jdbc:mysql://localhost:3306/minlia_dev?createDatabaseIfNotExist=true&useUnicode=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&verifyServerCertificate=false&useSSL=false&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
        name:
        username: root
        password:
#        使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        continue-on-error: true
        initialize: true

    redis:
        database: 0
        host: 127.0.0.1
        password:
        pool:
            max-active: 8
            max-idle: 8
            max-wait: -1
            min-idle: 0
        port: 6379
        timeout: 0

system.security.jwt:
    tokenExpirationTime: 10086 # Number of minutes
    refreshTokenExpTime: 10086 # Minutes
    tokenIssuer: http://minlia.com
    tokenSigningKey: minlia8EV6Hy5RMFK4EEACIDAwQus

swagger:
    title: ${spring.application.name}接口
    description: ${spring.application.name}接口
    version: 1.0
    contact: cloud@minlia.com
    path: /api/.*
    redirect: true

mybatis:
#    mapper-locations: classpath:com/minlia/module/bible/mapper/*.xml
    mapper-locations: classpath:mybatis/mapper/*.xml
    config-location:
        classpath: mybatis/mybatis-config.xml

aliyun:
    sms:
        accessId: xxxx
        accessKey: xxxx
        endpoint: cn-hangzhou
        regionId: cn-hangzhou
        product: Sms
        domain: sms.aliyuncs.com
        signName: 测试

sms:
    templates:
        userRegistration: SMS_56155265
        resetPassword: SMS_56155265
        changePassword: SMS_56155265
        bindOrRegistration: SMS_56155265
