server:
  port: 9999

system:
    appId: minlia-redis-app
    token: bWlubGlhCg==

spring:
    profile: dev
    application:
        name: Minlia Redis
    session:
        store-type: redis

    redis:
        database: 10
        host: 127.0.0.1
        port: 6379
        password:
        pool:
            max-active: 300
            max-wait: 10000
            max-idle: 50
            min-idle: 10
        timeout: 180

