server:
  port: 10006

system:
    appId: map-app
    token: bWlubGlhCg==

# SPRING PROFILES
spring:
    profile: dev
    application:
        name: Maps
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true
