server:
  port: 10002

system:
    appId: userinfo-app
    token: bWlubGlhCg==

# SPRING PROFILES
spring:
    profile: dev
    application:
        name: userinfo
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true

    datasource:
        driverClassName: net.sf.log4jdbc.DriverSpy
        url: jdbc:log4jdbc:mysql://localhost:3306/minlia_v1?createDatabaseIfNotExist=true&useUnicode=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&verifyServerCertificate=false&useSSL=false&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
        name:
        username: root
        password:
#        使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        continue-on-error: true
        initialize: true

    redis:
        database: 0
        host: 47.93.48.243
        password: yunka123
        pool:
            max-active: 8
            max-idle: 8
            max-wait: -1
            min-idle: 0
        port: 6379
        timeout: 0

system.security.jwt:
#  tokenExpirationTime: 15 # Number of minutes
  tokenExpirationTime: 604800 # Number of minutes
  refreshTokenExpTime: 604800 # Minutes
  tokenIssuer: http://minlia.com
  tokenSigningKey: minlia8EV6Hy5RMFK4EEACIDAwQus

swagger:
    title: ${spring.application.name}接口
    description: ${spring.application.name}接口
    version: 1.0
    contact: cloud@minlia.com
    path: /api/.*
    redirect: true

mybatis:
#  mapper-locations: classpath:com/minlia/module/bible/mapper/*.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#  config-location: classpath:mybatis/mybatis-config.xml

#jdbc:
#    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
#    url: jdbc:mysql://rm-bp1v94c921ols1ne60o.mysql.rds.aliyuncs.com/yuncard_dev?createDatabaseIfNotExist=true&useUnicode=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&verifyServerCertificate=false&useSSL=false&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false&allowMultiQueries=true
#    databaseName: yuncard_dev
#    serverName: 127.0.0.1
#    username: root
#    password: yuncard123!
#    cachePrepStmts: true
#    prepStmtsSize: 250
#    prepStmtsCacheSqlLimit: 2048
#    userServerPrepStmts: true

sms:
  templates:
    SECURITY_CODE: XXXX