server:
    port: 10014

system:
    appId: registryapp
    token: bWlubGlhCg==

spring:
    profile: dev
    application:
        name: registryapp


    datasource:
        testOnBorrow: true
        validationQuery: "SELECT 1"
#        driver-class-name: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        driverClassName: net.sf.log4jdbc.DriverSpy
        url: jdbc:log4jdbc:mysql://localhost:3306/minlia_cloud_registry_dev_v1?createDatabaseIfNotExist=true&useUnicode=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&verifyServerCertificate=false&useSSL=false&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
        name:
        username: root
        password:

security.jwt:
    tokenExpirationTime: 15 # Number of minutes
    refreshTokenExpTime: 60 # Minutes
    tokenIssuer: http://minlia.com
    tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus

swagger:
    title: ${spring.application.name}接口
    description: ${spring.application.name}接口
    version: 2.0
    contact: cloud@minlia.com
    path: /api/.*
